/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Shop_Portal;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Vikash Gupta
 */
public class Shopkeeper_form extends javax.swing.JFrame {
        Connection conn=null;
        Statement stmt=null;
        Connection myconnection()
 {
   try {
   Class.forName("com.mysql.cj.jdbc.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/","root","782456");
       }
    catch(Exception e)
       {
        }
    return conn;
  }
    /**
     * Creates new form Shopkeeper_form
     */
    public Shopkeeper_form() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        shopnametext = new javax.swing.JTextField();
        shopname = new javax.swing.JLabel();
        shopownername = new javax.swing.JLabel();
        shopownernametext = new javax.swing.JTextField();
        shopregistrationnumber = new javax.swing.JLabel();
        shopregistrationnumbertext = new javax.swing.JTextField();
        contactnumber = new javax.swing.JLabel();
        contactnumbertext = new javax.swing.JTextField();
        country = new javax.swing.JLabel();
        countrytext = new javax.swing.JTextField();
        state = new javax.swing.JLabel();
        statetext = new javax.swing.JTextField();
        districttext = new javax.swing.JTextField();
        pincode = new javax.swing.JLabel();
        pincodetext = new javax.swing.JTextField();
        district = new javax.swing.JLabel();
        addressline1 = new javax.swing.JLabel();
        addressline1text = new javax.swing.JTextField();
        addressline2 = new javax.swing.JLabel();
        addressline2text = new javax.swing.JTextField();
        submitdetail = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JLabel();
        passwordtext = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(94, 94, 112));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Shopkeeper Shop Address detail form");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        shopname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        shopname.setText("Shop name");

        shopownername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        shopownername.setText("Shop owner name");

        shopregistrationnumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        shopregistrationnumber.setText("Shop registration number");

        shopregistrationnumbertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopregistrationnumbertextActionPerformed(evt);
            }
        });

        contactnumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        contactnumber.setText("Contact number");

        country.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        country.setText("Country");

        state.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        state.setText("State");

        statetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statetextActionPerformed(evt);
            }
        });

        pincode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pincode.setText("Pincode");

        district.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        district.setText("District");

        addressline1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addressline1.setText("Address line 1");

        addressline2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addressline2.setText("Address line 2");

        submitdetail.setBackground(new java.awt.Color(0, 204, 0));
        submitdetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitdetail.setText("Submit detail ");
        submitdetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitdetailActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        password.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(shopname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shopnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shopownername)
                                    .addComponent(shopregistrationnumber)
                                    .addComponent(password))
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shopownernametext, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shopregistrationnumbertext, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitdetail, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(passwordtext)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(district)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addressline1)
                                .addComponent(addressline2))
                            .addComponent(country)
                            .addComponent(contactnumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(countrytext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressline2text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressline1text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(state)
                                .addGap(18, 18, 18)
                                .addComponent(statetext, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(districttext, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pincode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pincodetext, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(contactnumbertext, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shopname))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopownernametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shopownername))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shopregistrationnumbertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shopregistrationnumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password)
                    .addComponent(passwordtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactnumbertext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactnumber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(country)
                    .addComponent(countrytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state)
                    .addComponent(statetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(districttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pincode)
                        .addComponent(district))
                    .addComponent(pincodetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressline1)
                    .addComponent(addressline1text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressline2)
                    .addComponent(addressline2text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitdetail)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shopregistrationnumbertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopregistrationnumbertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shopregistrationnumbertextActionPerformed

    public void close()
    {
    WindowEvent win=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(win);
    }

    private void submitdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitdetailActionPerformed
    
    if(shopnametext.getText().isEmpty() || shopownernametext.getText().isEmpty() || shopregistrationnumbertext.getText().isEmpty() || passwordtext.getText().isEmpty() || contactnumbertext.getText().isEmpty() || countrytext.getText().isEmpty() || statetext.getText().isEmpty() || districttext.getText().isEmpty() || pincodetext.getText().isEmpty() || addressline1text.getText().isEmpty() || addressline2text.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fields can not be empty!!","Error",JOptionPane.WARNING_MESSAGE);
        }
else{    
    // TODO add your handling code here:
        String shopname=shopnametext.getText();
        String shopownername=shopownernametext.getText();
        String shopregistrationnumber=shopregistrationnumbertext.getText();
        String password=passwordtext.getText();
        String contactnumber=contactnumbertext.getText();
        String country=countrytext.getText();
        String state1=statetext.getText();
        String district=districttext.getText();
        String pincode=pincodetext.getText();
        String addressline1=addressline1text.getText();
        String addressline2=addressline2text.getText();
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop_portal","root","782456");
        Statement stmt=con.createStatement();
    //int id=5;
        String qry="insert into shopkeeper_table(shopname,shopownername,shopregistrationnumber,contactnumber,country,state1,district,pincode,addressline1,addressline2,password) values('"+shopname+"','"+shopownername+"','"+shopregistrationnumber+"','"+contactnumber+"','"+country+"','"+state1+"','"+district+"','"+pincode+"','"+addressline1+"','"+addressline2+"','"+password+"')";
        System.out.println(qry);
    int count=stmt.executeUpdate(qry);
    if(count>0)
    {
        JOptionPane.showMessageDialog(null,"Data saved successfully","Success",JOptionPane.INFORMATION_MESSAGE);
    Mobileshop_panel obj=new Mobileshop_panel();
    obj.setVisible(true);
    close();
    }
    else
        JOptionPane.showMessageDialog(null,"Failed to save data","details",JOptionPane.ERROR_MESSAGE);
        conn.close();
   }
catch(Exception e){ 
    e.printStackTrace();
            }
    }
    }//GEN-LAST:event_submitdetailActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Mobileshop_panel obj=new Mobileshop_panel();
    obj.setVisible(true);
    close();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void statetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statetextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shopkeeper_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shopkeeper_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shopkeeper_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shopkeeper_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shopkeeper_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressline1;
    private javax.swing.JTextField addressline1text;
    private javax.swing.JLabel addressline2;
    private javax.swing.JTextField addressline2text;
    private javax.swing.JLabel contactnumber;
    private javax.swing.JTextField contactnumbertext;
    private javax.swing.JLabel country;
    private javax.swing.JTextField countrytext;
    private javax.swing.JLabel district;
    private javax.swing.JTextField districttext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordtext;
    private javax.swing.JLabel pincode;
    private javax.swing.JTextField pincodetext;
    private javax.swing.JLabel shopname;
    private javax.swing.JTextField shopnametext;
    private javax.swing.JLabel shopownername;
    private javax.swing.JTextField shopownernametext;
    private javax.swing.JLabel shopregistrationnumber;
    private javax.swing.JTextField shopregistrationnumbertext;
    private javax.swing.JLabel state;
    private javax.swing.JTextField statetext;
    private javax.swing.JButton submitdetail;
    // End of variables declaration//GEN-END:variables
}
